name: jest

on:
  push:
    branches: [master, main]
    paths-ignore:
      - "test/testing.js"
      - ".npmignore"
      - ".gitignore"
  pull_request:
    branches: [master, main]
    paths-ignore:
      - "test/testing.js"
      - "npmignore"
      - ".gitignore"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test
